#!/usr/bin/env bash

domain="$1"
subdomain="$2"

get_record() {
    local sub="$1"
    local full="${sub}.${domain}"
    dig "$full" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain " "'"$sub"'" " is a " $4 " record and points to " $5}'
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_record "$sub"
    done
else
    get_record "$subdomain"
fi