#!/usr/bin/env bash
# Displays information about subdomains

# shellcheck disable=SC2086
display_info() {
    local domain=$1
    local subdomain=$2
    info=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tail -n 1)
    type=$(echo "$info" | awk '{print $4}')
    ip=$(echo "$info" | awk '{print $5}')
    echo "The subdomain ${subdomain} is a ${type} record and points to ${ip}"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    display_info "$domain" "$subdomain"
fi